CREATE TABLE LEAGUE
(
    LEAGUE_ID   NUMBER(4) PRIMARY KEY,
    LEAGUE_NAME VARCHAR2(30) NOT NULL UNIQUE,
    COUNTRY     VARCHAR2(20),
    CREATED_AT  TIMESTAMP,
    MODIFIED_AT TIMESTAMP
);

CREATE TABLE TEAM
(
    TEAM_ID      NUMBER(4) PRIMARY KEY,
    TEAM_NAME    VARCHAR2(20) UNIQUE NOT NULL,
    STADIUM_NAME VARCHAR2(20) UNIQUE NOT NULL,
    LOC          VARCHAR2(10)        NOT NULL,
    LEAGUE_ID    NUMBER(4),
    CREATED_AT   TIMESTAMP,
    MODIFIED_AT  TIMESTAMP,
    CONSTRAINT TEAM_FK FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE (LEAGUE_ID) ON DELETE SET NULL
);

CREATE TABLE USERS
(
    USER_ID     NUMBER(4) PRIMARY KEY,
    USER_NAME   VARCHAR2(30)       NOT NULL, -- ID(USER_NAME 으로 로그인)
    PASSWORD    VARCHAR(70) UNIQUE NOT NULL,
    ROLE        VARCHAR2(10)       NOT NULL,
    ADDRESS     VARCHAR2(100),
    CREATED_AT  TIMESTAMP,
    MODIFIED_AT TIMESTAMP
);

CREATE TABLE PLAYER
(
    PLAYER_ID   NUMBER(4) PRIMARY KEY,
    PLAYER_NAME VARCHAR2(30) NOT NULL,
    AGE         NUMBER(3)    NOT NULL,
    HEIGHT      NUMBER(4)    NOT NULL,
    TEAM_ID     NUMBER(4),
    USER_ID     NUMBER(4),
    CREATED_AT  TIMESTAMP,
    MODIFIED_AT TIMESTAMP,
    CONSTRAINT PLAYER_FK2 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE SET NULL,
    CONSTRAINT PLAYER_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID) ON DELETE SET NULL
);

CREATE SEQUENCE LEAGUE_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 5
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE TEAM_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 50
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE PLAYER_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 100
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE USERS_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 100
    NOCYCLE
    NOCACHE;

/* ==== 더미데이터 추가(반드시 순서대로!) ==== */
INSERT INTO LEAGUE
VALUES (LEAGUE_SEQ.nextval, 'Premier League', 'England', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));
INSERT INTO LEAGUE
VALUES (LEAGUE_SEQ.nextval, 'Bundesliga', 'Germany', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));
INSERT INTO LEAGUE
VALUES (LEAGUE_SEQ.nextval, 'LaLiga', 'Spain', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));

INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'Manchester United', 'Old Trafford', 'Manchester', 1, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));
INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'Manchester City', 'Etihad Stadium', 'Manchester', 1, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));

INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'FC Bayern Munchen', 'Allianz Arena', 'Bayern', 2, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));
INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'Borussia Dortmund', 'Signal Iduna Park', 'Dortmund', 2,
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));

INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'FC Barcelona', 'Camp Nou', 'Barcelona', 3, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));
INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'Real Madrid', 'Santiago Bernabeu', 'Madrid', 3, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));

COMMIT;