CREATE TABLE LEAGUE
(
    LEAGUE_ID   NUMBER(4) PRIMARY KEY,
    LEAGUE_NAME VARCHAR2(30),
    COUNTRY     VARCHAR2(20),
    CREATED_AT  TIMESTAMP,
    MODIFIED_AT TIMESTAMP
);

CREATE TABLE TEAM
(
    TEAM_ID      NUMBER(4) PRIMARY KEY,
    TEAM_NAME    VARCHAR2(20) NOT NULL UNIQUE,
    STADIUM_NAME VARCHAR2(20) NOT NULL UNIQUE,
    LOC          VARCHAR2(10) NOT NULL,
    CREATED_AT   TIMESTAMP,
    MODIFIED_AT  TIMESTAMP,
    LEAGUE_ID    NUMBER(4),
    CONSTRAINT FK FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE (LEAGUE_ID) ON DELETE SET NULL
);

CREATE TABLE PLAYER
(
    PLAYER_ID   NUMBER(4) PRIMARY KEY,
    PLAYER_NAME VARCHAR2(30),
    AGE         NUMBER(3),
    HEIGHT      NUMBER(4),
    CREATED_AT  TIMESTAMP,
    TEAM_ID     NUMBER(4),
    CONSTRAINT PLAYER_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID) ON DELETE SET NULL
);

CREATE SEQUENCE LEAGUE_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 5
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE TEAM_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 50
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE PLAYER_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 100
    NOCYCLE
    NOCACHE;

/* ==== 더미데이터 추가(반드시 순서대로!) ==== */
INSERT INTO LEAGUE
VALUES (LEAGUE_SEQ.nextval, 'Premier League', 'England', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));
INSERT INTO LEAGUE
VALUES (LEAGUE_SEQ.nextval, 'Bundesliga', 'Germany', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));
INSERT INTO LEAGUE
VALUES (LEAGUE_SEQ.nextval, 'LaLiga', 'Spain', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'));

INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'Manchester United', 'Old Trafford', 'Manchester', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 1);
INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'Manchester City', 'Etihad Stadium', 'Manchester', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 1);

INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'FC Bayern Munchen', 'Allianz Arena', 'Bayern', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 2);
INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'Borussia Dortmund', 'Signal Iduna Park', 'Dortmund', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 2);

INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'FC Barcelona', 'Camp Nou', 'Barcelona', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 3);
INSERT INTO TEAM
VALUES (TEAM_SEQ.nextval, 'Real Madrid', 'Santiago Bernabeu', 'Madrid', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'),
        TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 3);

INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'Antony', 25, 174, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 1);
INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'Maguire', 32, 194, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 1);

INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'Haaland', 25, 195, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 2);
INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'De Bruyne', 34, 181, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 2);

INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'Harry Kane', 32, 188, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 3);
INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'KIM', 29, 190, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 3);

INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'Jadon Sancho', 25, 180, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 4);
INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'Marcel Sabitzer', 31, 178, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 4);

INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'Frenkie de Jong', 28, 181, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 5);
INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'Robert Lewandowski', 37, 187, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 5);

INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'Rodrygo', 24, 174, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 6);
INSERT INTO PLAYER
VALUES (PLAYER_SEQ.nextval, 'Jude Bellingham', 22, 186, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 6);

COMMIT;